echo 'alias gw="cliferay gw"'
echo 'alias cdc="cd \$(cliferay source-folder)"'
echo 'alias cdl="cd \$(cliferay home)"'
echo 'alias c="cliferay"'
echo 'alias cc="claude --dangerously-skip-permissions"'
